### ISSUE TITLE
Any recommendations on how to reduce aliasing in the audio when using Audiokit 5? 

### ISSUE THREAD

**Issue by 01GOD** [NickCulbertson/AUv3-Instrument#1]
Thanks for posting that and that tutorial!
Any recommendations on how to reduce aliasing in the audio when using Audiokit 5? Built something simple with that a while ago and it sounded a little too rough. 

Thanks in advance!

**Comment by NickCulbertson** [comment]
Where were you getting aliasing, in the AUv3 or standalone?

If it is standalone, you can increase the bufferLength in the app delegate to reduce crackling.

**Comment by 01GOD** [comment]
Saw now. Thanks! I can look at that again. Think it was the AU though.

**Comment by 01GOD** [comment]
Listened again. Basically it sounds "clicky" sometimes when releasing a note. Sounded a little better when updated AudioKit to a newer version...before that broke the project...
"The package product 'AudioKitEX' requires minimum platform version 13.0 for the iOS platform, but this target supports 11.0" 

So downloaded the newer version of this repo and the included instrument worked (nice HARPsichord in the upper range there, that brought Me back to Versailles some). Would LOVE to be in Versailles today if any friends or acquaintances there would like a housemate that looks as though from there. 

Anyway brought the files over and xcode wanted to play compiler wack-a-mole for a while for no reason so cleaned the build folder and restarted xcode. Sigh...

So now it's functioning with the newer versions. For some reason in Garageband the instrument  still sounds a little "noisy" sometimes. Also sounds a little "clicky" sometimes when arping. Recommend solutions to that in the AU? Maybe it's caused by aliasing...I don't know for sure about what causes that. Thanks in advance!
(Found out that the arp mode in Garageband doesn't always respond to key presses instantly because of quantization)

Now thankfully have an AU plugin that would have been in the top 5 bout 20 calendar years ago. LOL. I guess the name of the game these days is making synth apps that sound instantly good with only one or two knobs and a fun interface. Would like to slap a scenekit metal or GLSL GUI onto that AU somehow. Somehow EASY that is...LOL. 

PS: A little sad how much of native Apple platform software engineering has been hassling with dysfunctional tools. Thanks for resiliently making those public repos with nice app templates!

**Comment by 01GOD** [comment]
Thought I should mention a repo that enabled a more open license specifically so that AudioKit can integrate a diode ladder filter emulation that (HOPEFULLY) actually functions nicely...unlike the sad Csound emulation: 
https://github.com/VoggLyster/DiodeLadderFilter

If are comfy with the low level AudioKit stuff in C and would be up for collaborating on porting that, I would be up for assisting with that. An AudioKit contributor bailed on porting that a while ago. Seems some people don't want to touch filter maths. Could also probably fix that Csound port relatively easily if somebody that is comfy with the low level AudioKit framework can assist with that.

**Comment by NickCulbertson** [comment]
The click sound on release is likely the release time of the EXS instrument being too fast. That would need to be a consideration when exporting the instrument from Logic's Sampler. For filters, AppleSampler() instruments have their own internal Low Pass filter you can map to in Logic's Sampler when creating an EXS. That is the one I typically use, but I like the MoogLadder alright too.

**Comment by 01GOD** [comment]
Saw now. Thanks! Actually tried adding an ADSR (because remembered how important adjusting attack and release have been for some clicky instruments) to the oscillator instrument yesterday. Haven't used EXS with AudioKit yet. (Aside from the examples)

Still maybe adjusting the general ADSR more, although thankfully it sounds nice enough to ship now. Last 2 hopefully small hurdles to handle are "WHERE to rename the AU so it ACTUALLY shows that new name in Garageband and so on???" because renamed multiple targets and in build settings and so on and it stiill has said the vanilla AU name. That was one of those "staring at Xcode wondering HOW a software company as large and wealthy as Apple could make such inadequate and RIDICULOUS tools" moments. 

Also...REALLY hope that it's not necessary to distribute a standalone app with an AU when uploading an AU to the App Store. Possible to simply upload and distribute an AU without also uploading an associated app? 

Was ready to ship a fun AU instrument today (aside from the icon) and then noticed those 2 final little issues. The interwubs haven't seemed to be so chock full of "making native AU instruments" QA sessions.

**Comment by NickCulbertson** [comment]
It looks like you got it sorted. Yeah, it has to be distributed with an app. AudioKit Pro released a Reverb app that is an AUv3 Reverb but in the standalone app it just has a tutorial video and a link to the source code in the app. Good luck with your app!
