### ISSUE TITLE
Weirdly the first build archive uploaded to App Store Connect had the AU bundle ID, but subsequent builds had the main App bundle ID. 

### ISSUE THREAD

**Issue by 01GOD** [NickCulbertson/AUv3-Instrument#2]
Weirdly the first build archive uploaded to App Store Connect had the AU bundle ID, but subsequent builds had the main App bundle ID. 
Hadn't changed those after the first upload. Already tried changing the scheme and building another archive. 

Know of a way to force the archive to use the AU bundle ID again instead of the main App bundle ID? So weird that Xcode did that once and not again after. Having a build with a main app and an AU extension both in the same build is unique. 

Thanks in advance for posting a solution!

**Comment by NickCulbertson** [comment]
I'm not sure what is going on. This part is always a bit of a headache to setup the first time. Your names should be like this:

App Bundle ID: com.DevName.AppName
AU Bundle ID: com.DevName.AppName.ExtensionName

They both get signed and uploaded. The App Store uses the App Bundle ID. You need a separate provisioning profile for both the app and the AU.

**Comment by NickCulbertson** [comment]
Send me an email next time if you have questions. That's easier for me to get to than GitHub issues and YouTube comments. hello@mobypixel.com
