### ISSUE TITLE
Resolving Package Graph Failed    02.04.23, 18:51    17.1 seconds

### ISSUE THREAD

**Issue by luto65** [NickCulbertson/AUv3-Instrument#4]
Hi,
I am on Xcode13, I first had "Package.resolved file is corrupted or malformed, then I removed it ( following the https://stackoverflow.com/questions/67185817/package-resolved-file-is-corrupted-or-malformed)
and now I got the following error
Couldn’t get revision ‘main^{commit}’:
Resolving Package Graph Failed  
Any hint ?

From other threads I have the impression that perhaps i should upgrade to XCode14 or I should get an older build of AudioKit..
Perhaps that's the origin and the cure ?

**Comment by NickCulbertson** [comment]
I’ll look into it tomorrow. You could try downloading a fresh install and “clear package caches”. That sometimes resolves these issues but it could be that something changed with the version of AK that is targeted.Sent from my iPhoneOn Apr 2, 2023, at 12:57 PM, luto65 ***@***.***> wrote:﻿
Hi,
I am on Xcode13, I first had "Package.resolved file is corrupted or malformed, then I removed it ( following the https://stackoverflow.com/questions/67185817/package-resolved-file-is-corrupted-or-malformed)
and now I got the following error
Couldn’t get revision ‘main^{commit}’:
Resolving Package Graph Failed
Any hint ?
From other threads I have the impression that perhaps i should upgrade to XCode14 or I should get an older build of AudioKit..
Perhaps that's the origin and the cure ?

**Comment by NickCulbertson** [comment]
I just tried downloading a fresh install, selecting File > Packages > Reset Package Caches, and everything ran properly. I am on Xcode 14. I'm not sure what the issue could be with running on Xcode 13. It is possible you could remove the AudioKit and Keyboard packages from your build settings, then re-add them manually.
